version: 2
run:
  timeout: 5m
  tests: true
linters-settings:
  gocyclo:
    min-complexity: 15
  goconst:
    min-len: 3
    min-occurrences: 3
  govet:
    enable-all: true
linters:
  enable:
    - govet
    - revive
    - gocyclo
    - goconst
    - staticcheck
    - ineffassign
    - unconvert
    - misspell
    - errcheck
    - gosec
