# GoReleaser configuration for dotnet-dockerfile-gen
# See https://goreleaser.com for full reference.
version: 2
project_name: dockerfile-gen

before:
  hooks:
    - go mod tidy

builds:
  - id: dotnet-dockerfile-gen
    main: .
    binary: dotnet-dockerfile-gen
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
    flags:
      - -trimpath

archives:
  - id: default
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    files:
      - README.md
      - LICENSE* # optional, included if present

checksum:
  name_template: 'checksums.txt'

# Docker image build/publish is handled by GitHub Actions workflow 'docker-image' job.

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - '^ci:'

snapshot:
  version_template: '{{ .Tag }}-next'

dist: dist

release:
  draft: false
  prerelease: auto

git:
  tag_sort: -version:refname
